name: Build scikit-learn

on:
  workflow_dispatch:

permissions:
   contents: read  # to fetch code (actions/checkout)

jobs:
  build_scikit_learn:
    name: Build scikit-learn on Python 3.9
    runs-on: macos-11

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v3
        with:
          repository: scikit-learn/scikit-learn
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python3 -m pip install cython numpy wheel

      - name: Get scipy wheel
        run: wget -O scipy-1.11.0.dev0-cp39-cp39-macosx_10_9_x86_64.whl https://github.com/lysnikolaou/scipy-scikitlearn-wheels/raw/main/scipy-1.11.0.dev0-cp39-cp39-macosx_10_9_x86_64.whl

      - name: Install scipy from wheel
        run: python3 -m pip install ./scipy-1.11.0.dev0-cp39-cp39-macosx_10_9_x86_64.whl

      - name: Build scikit-learn
        run: pip install --verbose --no-build-isolation --editable .

      - name: Test
        run: python3 -c "import sklearn; sklearn.show_versions()"
