name: Build scikit-learn-wheel

on:
  workflow_dispatch:

permissions:
   contents: read  # to fetch code (actions/checkout)

jobs:
  build_wheels:
    name: Build scipy wheel for Python 3.9
    runs-on: macos-11

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v3
        with:
          repository: scikit-learn/scikit-learn
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Get scipy wheel
        run: wget -O scipy-1.11.0.dev0-cp39-cp39-macosx_10_9_x86_64.whl https://github.com/lysnikolaou/scipy-scikitlearn-wheels/raw/main/scipy-1.11.0.dev0-cp39-cp39-macosx_10_9_x86_64.whl

      - name: Edit pyproject.toml to install wheel
        run: |
          sed -i '' 's/scipy>=1.5.0/scipy @ https:\/\/github.com\/lysnikolaou\/scipy-scikitlearn-wheels\/raw\/main\/scipy-1.11.0.dev0-cp39-cp39-macosx_10_9_x86_64.whl/' pyproject.toml
          cat pyproject.toml

      - name: Build wheel
        env:
          CONFTEST_PATH: ${{ github.workspace }}/conftest.py
          CONFTEST_NAME: conftest.py
          CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
                            SKLEARN_BUILD_PARALLEL=3
          CIBW_BUILD: cp39-macosx*
          CIBW_TEST_SKIP: "*"
          CIBW_BUILD_VERBOSITY: 1
          CONDA_HOME: /usr/local/miniconda
        run: bash build_tools/wheels/build_wheels.sh

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
