name: Test scikit-learn built with scipy-dev

on:
  workflow_dispatch:

permissions:
   contents: read  # to fetch code (actions/checkout)

jobs:
  build_scikit_learn:
    name: Build scikit-learn on Python 3.9
    runs-on: macos-11

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python3 -m pip install scipy https://github.com/lysnikolaou/scipy-scikitlearn-wheels/raw/main/scikit_learn-1.3.dev0-cp39-cp39-macosx_10_9_x86_64.whl

      - name: Test
        run: python3 -c "from sklearn.utils._cython_blas import _asum_memview; import numpy as np; x = np.array([[1, 2], [3, 4]], dtype=np.float32); _asum_memview(x)"
