name: Wheel builder

on:
  workflow_dispatch:

permissions:
   contents: read  # to fetch code (actions/checkout)

jobs:
  build_wheels:
    name: Build wheel for Python 3.9
    runs-on: macos-11

    steps:
      - name: Checkout scipy
        uses: actions/checkout@v3
        with:
          repository: scipy/scipy
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Get into scipy
        run: cd scipy

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_BUILD: cp39-macosx*
          CIBW_ENVIRONMENT_MACOS: >
            SDKROOT=/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
            LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
            MACOSX_DEPLOYMENT_TARGET=10.9
            MACOS_DEPLOYMENT_TARGET=10.9
            _PYTHON_HOST_PLATFORM=macosx-10.9-x86_64
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            DYLD_LIBRARY_PATH=/usr/local/lib delocate-listdeps {wheel} &&
            DYLD_LIBRARY_PATH=/usr/local/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          name: cp39-macosx*
